FROM ubuntu:16.04

ARG http_proxy

ARG https_proxy

ENV http_proxy ${http_proxy}

ENV https_proxy ${https_proxy}

RUN echo $https_proxy

RUN echo $http_proxy

# Uncomment the two lines below if you wish to use an Ubuntu mirror repository
# that is closer to you (and hence faster). The 'sources.list' file inside the
# 'tools/docker/' folder is set to use one of Ubuntu's official mirror in Taiwan.
# You should update this file based on your own location. For a list of official
# Ubuntu mirror repositories, check out: https://launchpad.net/ubuntu/+archivemirrors
COPY sources.list /etc/apt
RUN rm /var/lib/apt/lists/* -vf

RUN apt-get clean && apt-get update

#RUN apt install -y npm nodejs nodejs-dev nodejs-legacy
RUN apt install -y npm nodejs-legacy

RUN apt install -y libzmq3-dev libkrb5-dev

COPY face-access-control /opt/face-access-control/ 

WORKDIR /opt/face-access-control/webservice/server

RUN npm config set proxy $http_proxy

RUN npm config set https-proxy $https_proxy

RUN npm install

WORKDIR /opt/face-access-control/webservice/front-end

RUN npm install

WORKDIR /opt/face-access-control/webservice/

ENV http_proxy ""

ENV https_proxy ""
